### ISSUE TITLE
the dots all have the same radius now...

### ISSUE THREAD

**Issue by pletzer** [mkienzle/MachineLearning#12]
is this intended?

**Comment by mkienzle** [comment]
yes, I simplified the synthetic data to get better results. But following
our phone conversation that might not suit you. Anyhow, we could always put
an argument to let the user decide whether they want same or varying
radiuses.

**Comment by pletzer** [comment]
I got really good results with a convolution NN using dots of variable size so I think forcing large radii is no longer needed.

**Comment by mkienzle** [comment]
sounds very good: we ll revert back to variable radii

**Comment by mkienzle** [comment]
resolved by @pletzer
